version: "3.9"
services:
  app:
    image: "${ECR_REPO_URL}:latest"
    env_file:
      - /opt/app/.env  # եթե պետք լինի
    ports:
      - "5000:5000"
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    depends_on:
      - app
    volumes:
      - /opt/app/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped
