name: CI-CD Pipeline 

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Code analysis
        uses: actions/SonarSource/sonarcloud-github-action@v2
      - name: Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Flask
        run: |
          python -m pip install --upgrade pip
          pip install flask
      - name: test
        run: |
          pytest || echo "No tests found"
  docker:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Dockerscan
        uses: aquasecurity/trivy-action@0.28.0     
     with:
        scan-type: 'fs'
        scan-ref: '.'
        trivy-config: trivy.yaml
   ECR:
      -name: Terraform
      
      
